apiVersion: v1
kind: Secret
metadata:
  name: task-platform-secret
  namespace: task-platform
type: Opaque
stringData:
  POSTGRES_DB: taskdb
  POSTGRES_USER: taskuser
  POSTGRES_PASSWORD: taskpassword